### PR TITLE
Remove unintential render after each getAccessToken* call

### LINKED ISSUE #155: CRA and Gatsby integration tests are failing
### Describe the problem

There's a few issues here:

- The Gatsby and CRA tests are failing but the [CI isn't picking them up](https://app.circleci.com/pipelines/github/auth0/auth0-react/295/workflows/d474e81c-18e7-40b8-acdc-d29522069ea3/jobs/307/tests), it's passing because our script to run the test chains 3 commands, so when the last one succeeds the other 2 failures are ignored, eg `exit 1; exit 1; exit 0` = `exit 0`
- Our `ProtectedRoute` example code in the create-react-app example https://github.com/auth0/auth0-react/blob/master/examples/cra-react-router/src/ProtectedRoute.tsx and https://github.com/auth0/auth0-react/blob/master/examples/gatsby-app/src/components/ProtectedRoute.js causes the protected component to remount each time the app renders. The react-router example should use a `render` prop rather than `component` (see: https://reactrouter.com/web/api/Route/component). The `reach-router` example should just avoid the inline function that returns a protected component all together.
- Our solution to https://github.com/auth0/auth0-react/pull/146 is flawed, even though the user object reference doesn't change, the Context's `value` will be a new reference and when that changes the Provider will cause all routes underneath to render (see https://reactjs.org/docs/context.html#caveats). So any call to `getAccessTokenSilently` will cause a rerender, which is undesirable.

### PR DESCRIPTION
**Pull request by adamjmcgrath**
### Description

- Fix issue where CI wasn't picking up failing Gatsby and CRA tests
- Any updates in the provider will trigger a new render of child components so only dispatch the user update when the `updated_at` date has changed (this should satisfy #135)
- Fix the Gatsby and CRA examples, `ProtectedRoute` shouldn't remount every time the app rerenders

### References

Fixes #155 

### Testing

- [x] This change adds test coverage for new/changed/fixed functionality

### Checklist

- [x] I have added documentation for new/changed functionality in this PR or in auth0.com/docs
- [x] All active GitHub checks for tests, formatting, and security are passing
- [x] The correct base branch is being used, if not `master`

### CODE REVIEW

**Review by stevehobbsdev — APPROVED** [review]

File: src/auth0-provider.tsx [hunk 1]
```diff
@@ -287,10 +291,12 @@ const Auth0Provider = (opts: Auth0ProviderOptions): JSX.Element => {
         throw tokenError(error);
       }
       const user = await client.getUser();
-      dispatch({ type: 'GET_TOKEN_COMPLETE', user });
+      if (user.updated_at !== userUpdatedAt) {
+        dispatch({ type: 'USER_UPDATED', user });
+      }
```
Comment (Amirault) [inline src/auth0-provider.tsx:296]: while isAuthenticated is linked to user_updated this prevent the isAuthenticated update while the token is not expired... IMO  there another action 'TOKEN_REFRESHED' (or something similar) outside of this if

Comment (adamjmcgrath) [reply src/auth0-provider.tsx:296]: Hey @Amirault - thanks for your feedback!

> while isAuthenticated is linked to user_updated this prevent the isAuthenticated update while the token is not expired... 

Could you explain this issue a bit more, with an example if possible - I'm not sure I understand what the problem is
